//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visao.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visao.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap abono24 {
            get {
                object obj = ResourceManager.GetObject("abono24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap abono32 {
            get {
                object obj = ResourceManager.GetObject("abono32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add16 {
            get {
                object obj = ResourceManager.GetObject("add16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add24 {
            get {
                object obj = ResourceManager.GetObject("add24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add32 {
            get {
                object obj = ResourceManager.GetObject("add32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add48 {
            get {
                object obj = ResourceManager.GetObject("add48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add64 {
            get {
                object obj = ResourceManager.GetObject("add64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Advogado16x16 {
            get {
                object obj = ResourceManager.GetObject("Advogado16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Advogado24x24 {
            get {
                object obj = ResourceManager.GetObject("Advogado24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Advogado32x32 {
            get {
                object obj = ResourceManager.GetObject("Advogado32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap appadd16 {
            get {
                object obj = ResourceManager.GetObject("appadd16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap appadd24 {
            get {
                object obj = ResourceManager.GetObject("appadd24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap appadd32 {
            get {
                object obj = ResourceManager.GetObject("appadd32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap appadd48 {
            get {
                object obj = ResourceManager.GetObject("appadd48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap appadd64 {
            get {
                object obj = ResourceManager.GetObject("appadd64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap atend128 {
            get {
                object obj = ResourceManager.GetObject("atend128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap atend16 {
            get {
                object obj = ResourceManager.GetObject("atend16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap atend32 {
            get {
                object obj = ResourceManager.GetObject("atend32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap atend64 {
            get {
                object obj = ResourceManager.GetObject("atend64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back128 {
            get {
                object obj = ResourceManager.GetObject("back128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back16 {
            get {
                object obj = ResourceManager.GetObject("back16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back24 {
            get {
                object obj = ResourceManager.GetObject("back24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back32 {
            get {
                object obj = ResourceManager.GetObject("back32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back48 {
            get {
                object obj = ResourceManager.GetObject("back48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back64 {
            get {
                object obj = ResourceManager.GetObject("back64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cabeca32 {
            get {
                object obj = ResourceManager.GetObject("cabeca32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cad128 {
            get {
                object obj = ResourceManager.GetObject("cad128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cad16 {
            get {
                object obj = ResourceManager.GetObject("cad16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cad24 {
            get {
                object obj = ResourceManager.GetObject("cad24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cad32 {
            get {
                object obj = ResourceManager.GetObject("cad32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cad48 {
            get {
                object obj = ResourceManager.GetObject("cad48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calculator_16x16 {
            get {
                object obj = ResourceManager.GetObject("calculator_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calculator_24x24 {
            get {
                object obj = ResourceManager.GetObject("calculator_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calculator_32x32 {
            get {
                object obj = ResourceManager.GetObject("calculator_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap canc {
            get {
                object obj = ResourceManager.GetObject("canc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap canc24 {
            get {
                object obj = ResourceManager.GetObject("canc24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cliente128 {
            get {
                object obj = ResourceManager.GetObject("cliente128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cliente64 {
            get {
                object obj = ResourceManager.GetObject("cliente64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap coffee {
            get {
                object obj = ResourceManager.GetObject("coffee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap coffee_stain {
            get {
                object obj = ResourceManager.GetObject("coffee_stain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf128 {
            get {
                object obj = ResourceManager.GetObject("conf128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf24 {
            get {
                object obj = ResourceManager.GetObject("conf24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf32 {
            get {
                object obj = ResourceManager.GetObject("conf32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf48 {
            get {
                object obj = ResourceManager.GetObject("conf48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConsAvancada16x16 {
            get {
                object obj = ResourceManager.GetObject("ConsAvancada16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConsAvancada24x24 {
            get {
                object obj = ResourceManager.GetObject("ConsAvancada24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConsAvancada32x32 {
            get {
                object obj = ResourceManager.GetObject("ConsAvancada32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConsProcessoCliente16x16 {
            get {
                object obj = ResourceManager.GetObject("ConsProcessoCliente16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConsProcessoCliente24x24 {
            get {
                object obj = ResourceManager.GetObject("ConsProcessoCliente24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConsProcessoCliente32x32 {
            get {
                object obj = ResourceManager.GetObject("ConsProcessoCliente32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConsSimples16x16 {
            get {
                object obj = ResourceManager.GetObject("ConsSimples16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConsSimples24x24 {
            get {
                object obj = ResourceManager.GetObject("ConsSimples24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConsSimples32x32 {
            get {
                object obj = ResourceManager.GetObject("ConsSimples32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap convmoeda16x16 {
            get {
                object obj = ResourceManager.GetObject("convmoeda16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap convmoeda24 {
            get {
                object obj = ResourceManager.GetObject("convmoeda24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap convmoeda32x32 {
            get {
                object obj = ResourceManager.GetObject("convmoeda32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copiaindices16 {
            get {
                object obj = ResourceManager.GetObject("copiaindices16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copiaindices24 {
            get {
                object obj = ResourceManager.GetObject("copiaindices24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copiaindices32 {
            get {
                object obj = ResourceManager.GetObject("copiaindices32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap correcaoindice24 {
            get {
                object obj = ResourceManager.GetObject("correcaoindice24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap correcaoindice32 {
            get {
                object obj = ResourceManager.GetObject("correcaoindice32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap correcaoindice48 {
            get {
                object obj = ResourceManager.GetObject("correcaoindice48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap date16 {
            get {
                object obj = ResourceManager.GetObject("date16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap date24 {
            get {
                object obj = ResourceManager.GetObject("date24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap date32 {
            get {
                object obj = ResourceManager.GetObject("date32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap date48 {
            get {
                object obj = ResourceManager.GetObject("date48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap date64 {
            get {
                object obj = ResourceManager.GetObject("date64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EA_16x16 {
            get {
                object obj = ResourceManager.GetObject("EA_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EALOGO {
            get {
                object obj = ResourceManager.GetObject("EALOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap evo_24x24 {
            get {
                object obj = ResourceManager.GetObject("evo_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap evo_32x32 {
            get {
                object obj = ResourceManager.GetObject("evo_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap evot_16x16 {
            get {
                object obj = ResourceManager.GetObject("evot_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ferramentas16 {
            get {
                object obj = ResourceManager.GetObject("ferramentas16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ferramentas24 {
            get {
                object obj = ResourceManager.GetObject("ferramentas24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ferramentas32 {
            get {
                object obj = ResourceManager.GetObject("ferramentas32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fundo {
            get {
                object obj = ResourceManager.GetObject("Fundo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap graf24 {
            get {
                object obj = ResourceManager.GetObject("graf24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap graf32 {
            get {
                object obj = ResourceManager.GetObject("graf32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap grupo16 {
            get {
                object obj = ResourceManager.GetObject("grupo16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap grupo24 {
            get {
                object obj = ResourceManager.GetObject("grupo24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap grupo32 {
            get {
                object obj = ResourceManager.GetObject("grupo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap grupo64 {
            get {
                object obj = ResourceManager.GetObject("grupo64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hist128 {
            get {
                object obj = ResourceManager.GetObject("hist128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hist16 {
            get {
                object obj = ResourceManager.GetObject("hist16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hist24 {
            get {
                object obj = ResourceManager.GetObject("hist24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hist32 {
            get {
                object obj = ResourceManager.GetObject("hist32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hist64 {
            get {
                object obj = ResourceManager.GetObject("hist64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Honorarios16x16 {
            get {
                object obj = ResourceManager.GetObject("Honorarios16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Honorarios24x24 {
            get {
                object obj = ResourceManager.GetObject("Honorarios24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Honorarios32x32 {
            get {
                object obj = ResourceManager.GetObject("Honorarios32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap indice16 {
            get {
                object obj = ResourceManager.GetObject("indice16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap indice24 {
            get {
                object obj = ResourceManager.GetObject("indice24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap indice32 {
            get {
                object obj = ResourceManager.GetObject("indice32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap indice48 {
            get {
                object obj = ResourceManager.GetObject("indice48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap intervalo32 {
            get {
                object obj = ResourceManager.GetObject("intervalo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap intervaloabono24 {
            get {
                object obj = ResourceManager.GetObject("intervaloabono24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap intervaloabono32 {
            get {
                object obj = ResourceManager.GetObject("intervaloabono32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap limpar {
            get {
                object obj = ResourceManager.GetObject("limpar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] logo_Jardim_Advocacia {
            get {
                object obj = ResourceManager.GetObject("logo_Jardim_Advocacia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_Jardim_Advocacia1 {
            get {
                object obj = ResourceManager.GetObject("logo_Jardim_Advocacia1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo01 {
            get {
                object obj = ResourceManager.GetObject("logo01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] logo011 {
            get {
                object obj = ResourceManager.GetObject("logo011", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logo2 {
            get {
                object obj = ResourceManager.GetObject("Logo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logoJardim {
            get {
                object obj = ResourceManager.GetObject("logoJardim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logout16x16 {
            get {
                object obj = ResourceManager.GetObject("Logout16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logout24x24 {
            get {
                object obj = ResourceManager.GetObject("Logout24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logout32x32 {
            get {
                object obj = ResourceManager.GetObject("Logout32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Minimizar16x16 {
            get {
                object obj = ResourceManager.GetObject("Minimizar16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Minimizar24x24 {
            get {
                object obj = ResourceManager.GetObject("Minimizar24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Minimizar32x32 {
            get {
                object obj = ResourceManager.GetObject("Minimizar32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap msg24 {
            get {
                object obj = ResourceManager.GetObject("msg24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MSG32 {
            get {
                object obj = ResourceManager.GetObject("MSG32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap next16 {
            get {
                object obj = ResourceManager.GetObject("next16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap next24 {
            get {
                object obj = ResourceManager.GetObject("next24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap next32 {
            get {
                object obj = ResourceManager.GetObject("next32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap next48 {
            get {
                object obj = ResourceManager.GetObject("next48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap next64 {
            get {
                object obj = ResourceManager.GetObject("next64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OK16 {
            get {
                object obj = ResourceManager.GetObject("OK16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OK24 {
            get {
                object obj = ResourceManager.GetObject("OK24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OK32 {
            get {
                object obj = ResourceManager.GetObject("OK32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OK48 {
            get {
                object obj = ResourceManager.GetObject("OK48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OK64 {
            get {
                object obj = ResourceManager.GetObject("OK64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap param128 {
            get {
                object obj = ResourceManager.GetObject("param128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap param16 {
            get {
                object obj = ResourceManager.GetObject("param16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap param24 {
            get {
                object obj = ResourceManager.GetObject("param24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap param32 {
            get {
                object obj = ResourceManager.GetObject("param32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap param48 {
            get {
                object obj = ResourceManager.GetObject("param48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pdf_16x16 {
            get {
                object obj = ResourceManager.GetObject("pdf_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pdf_24x24 {
            get {
                object obj = ResourceManager.GetObject("pdf_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pdf_32x32 {
            get {
                object obj = ResourceManager.GetObject("pdf_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pend16 {
            get {
                object obj = ResourceManager.GetObject("pend16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pend24 {
            get {
                object obj = ResourceManager.GetObject("pend24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pend32 {
            get {
                object obj = ResourceManager.GetObject("pend32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pend64 {
            get {
                object obj = ResourceManager.GetObject("pend64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap preco128 {
            get {
                object obj = ResourceManager.GetObject("preco128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap preco16 {
            get {
                object obj = ResourceManager.GetObject("preco16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap preco24 {
            get {
                object obj = ResourceManager.GetObject("preco24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap preco32 {
            get {
                object obj = ResourceManager.GetObject("preco32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap preco48 {
            get {
                object obj = ResourceManager.GetObject("preco48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap prim16 {
            get {
                object obj = ResourceManager.GetObject("prim16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap prim24 {
            get {
                object obj = ResourceManager.GetObject("prim24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap prim32 {
            get {
                object obj = ResourceManager.GetObject("prim32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap prim48 {
            get {
                object obj = ResourceManager.GetObject("prim48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap prim64 {
            get {
                object obj = ResourceManager.GetObject("prim64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap processo128 {
            get {
                object obj = ResourceManager.GetObject("processo128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap processo16 {
            get {
                object obj = ResourceManager.GetObject("processo16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap processo24 {
            get {
                object obj = ResourceManager.GetObject("processo24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap processo32 {
            get {
                object obj = ResourceManager.GetObject("processo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap processo48 {
            get {
                object obj = ResourceManager.GetObject("processo48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap processo64 {
            get {
                object obj = ResourceManager.GetObject("processo64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcuracaoINSS16x16 {
            get {
                object obj = ResourceManager.GetObject("ProcuracaoINSS16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcuracaoINSS24x24 {
            get {
                object obj = ResourceManager.GetObject("ProcuracaoINSS24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcuracaoINSS32x32 {
            get {
                object obj = ResourceManager.GetObject("ProcuracaoINSS32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh16 {
            get {
                object obj = ResourceManager.GetObject("refresh16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh24 {
            get {
                object obj = ResourceManager.GetObject("refresh24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh32 {
            get {
                object obj = ResourceManager.GetObject("refresh32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap remove16 {
            get {
                object obj = ResourceManager.GetObject("remove16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap remove24 {
            get {
                object obj = ResourceManager.GetObject("remove24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap remove32 {
            get {
                object obj = ResourceManager.GetObject("remove32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap remove48 {
            get {
                object obj = ResourceManager.GetObject("remove48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap remove64 {
            get {
                object obj = ResourceManager.GetObject("remove64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sair16 {
            get {
                object obj = ResourceManager.GetObject("sair16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sair24 {
            get {
                object obj = ResourceManager.GetObject("sair24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sair32 {
            get {
                object obj = ResourceManager.GetObject("sair32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SairPrograma16x16 {
            get {
                object obj = ResourceManager.GetObject("SairPrograma16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SairPrograma24x24 {
            get {
                object obj = ResourceManager.GetObject("SairPrograma24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SairPrograma32x32 {
            get {
                object obj = ResourceManager.GetObject("SairPrograma32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap salario24 {
            get {
                object obj = ResourceManager.GetObject("salario24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap salario32 {
            get {
                object obj = ResourceManager.GetObject("salario32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_16x16 {
            get {
                object obj = ResourceManager.GetObject("search_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_24x24 {
            get {
                object obj = ResourceManager.GetObject("search_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_32x32 {
            get {
                object obj = ResourceManager.GetObject("search_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_48x48 {
            get {
                object obj = ResourceManager.GetObject("search_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_64x64 {
            get {
                object obj = ResourceManager.GetObject("search_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap senha32 {
            get {
                object obj = ResourceManager.GetObject("senha32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tabelafria32 {
            get {
                object obj = ResourceManager.GetObject("tabelafria32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tabelaquente32 {
            get {
                object obj = ResourceManager.GetObject("tabelaquente32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TOOL_16x16 {
            get {
                object obj = ResourceManager.GetObject("TOOL_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TOOL_32x32 {
            get {
                object obj = ResourceManager.GetObject("TOOL_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ult16 {
            get {
                object obj = ResourceManager.GetObject("ult16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ult24 {
            get {
                object obj = ResourceManager.GetObject("ult24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ult32 {
            get {
                object obj = ResourceManager.GetObject("ult32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ult48 {
            get {
                object obj = ResourceManager.GetObject("ult48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ult64 {
            get {
                object obj = ResourceManager.GetObject("ult64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap usuario16 {
            get {
                object obj = ResourceManager.GetObject("usuario16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap usuario24 {
            get {
                object obj = ResourceManager.GetObject("usuario24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap usuario32 {
            get {
                object obj = ResourceManager.GetObject("usuario32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
